/*
 * Este software foi desenvolvido e criado por Rodrigo Attique Santana,
 * todos os algoritimos presentes aqui são de altoria do desenvolvedor, não sendo permitido
 * cópia ou distribuição sem o consentimento do mesmo.
 * É proibido vender, modificar, distribuir sem autorização.
 * copyright Attique Tecnologia.
 */
package views;

import controllers.ConfiguracoesController;
import controllers.EnderecoController;
import controllers.UsuarioController;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.Configuracoes;
import models.Endereco;
import models.enuns.Estados;
import models.enuns.InformacoesSistema;
import models.interfaces.DefaultComponent;
import models.interfaces.DefaultFormCadastro;
import models.tablemodels.MyTableModel;
import models.usuarios.CasoUso;
import models.usuarios.Permissao;
import models.usuarios.Sessao;

import utils.Log;
import models.usuarios.Usuario;
import persistence.TextFile;
import persistence.UsuarioBO;

import utils.ShowMessage;
import views.enderecos.FrmPesquisaEndereco;

import views.usuarios.FrmCadastroUsuario;

/**
 *
 * @author Rodrigo
 */
public class DlgConfiguracoes extends javax.swing.JDialog implements DefaultFormCadastro, DefaultComponent {
    /**
     * Variável de configurações;
     */
    private Configuracoes cfg;
    private String pathFoto;
    private List<Usuario> usuarios;
    private ConfiguracoesController controllerCfg;
    private InformacoesSistema info = InformacoesSistema.getInstance();
    private Endereco endereco;
    
    /**Encontra o caminho absoluto*/
    private static String pathAbsoluto = TextFile.getINSTANCE().getPathAbsoluto();

    private String pathRelativo;
    
    /**
     * Creates new form DlgConfiguracoes
     */
    public DlgConfiguracoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(null);
        
        controllerCfg = new ConfiguracoesController();
        cfg = new Configuracoes();
        pathRelativo = cfg.getPathDocumentos();
        usuarios = new ArrayList<>();
        
        //CARREGANDO ESTADOS
        cmbUf.setModel(new DefaultComboBoxModel(Estados.values()));
        cmbUf.setSelectedIndex(25);
        
        //CARREGANDO VALORES DO BANCO DE DADOS
        setDataForm(controllerCfg.findCfgDefault());
        
        procurarUsuario();
        
        //construindo informações
        lblSo.setText(info.getOsName());
        lblVersao.setText(info.getOsVersion());
        lblIp.setText(info.getIpAddress());
        lblHost.setText(info.getHostName());
        lblUsuario.setText(info.getUserName());
        lblPathSistema.setText(InformacoesSistema.PATH_SISTEMA);
        
        verPermissao();
        pnLogAcao.add("Logs Ação", new PnLogSistema());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnDadosEmpresa = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtRazaoSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnAddFoto = new javax.swing.JButton();
        btnRemFoto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        cmbUf = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnPesquisaCEP = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edpAnotacoes = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisaUsuario = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtPastaLogErro = new javax.swing.JTextField();
        btnPastaLogErro = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtPastaBackup = new javax.swing.JTextField();
        btnPastaBackup = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtPastaImpressao = new javax.swing.JTextField();
        btnPastaBackup1 = new javax.swing.JButton();
        lblIp = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblSo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblPathSistema = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtPastaDocumentos = new javax.swing.JTextField();
        btnPastaBackup2 = new javax.swing.JButton();
        txtPastaDados = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnPastaBackup3 = new javax.swing.JButton();
        pnLogAcao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/24x24/Save.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/24x24/Exit.png"))); // NOI18N
        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnDadosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Bairro");

        jLabel7.setText("Cidade");

        jLabel3.setText("CNPJ:");

        jLabel1.setText("Nome Fantasia:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Logomarca"));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAddFoto.setText("+");
        btnAddFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFotoActionPerformed(evt);
            }
        });

        btnRemFoto.setText("-");
        btnRemFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnRemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFoto)
                    .addComponent(btnRemFoto))
                .addContainerGap())
        );

        jLabel4.setText("CEP");

        jLabel2.setText("Razao Social:");

        jLabel8.setText("UF");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Endereco");

        jLabel26.setText("Telefones:");

        jLabel27.setText("Site:");

        jLabel28.setText("Email:");

        btnPesquisaCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Search.png"))); // NOI18N
        btnPesquisaCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazaoSocial)
                    .addComponent(txtNomeFantasia)
                    .addComponent(txtCnpj)
                    .addComponent(txtBairro)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCidade)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisaCEP))
                    .addComponent(cmbUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefone)
                    .addComponent(txtSite)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPesquisaCEP))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Geral", jPanel3);

        jScrollPane2.setViewportView(edpAnotacoes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Anotações", jPanel6);

        javax.swing.GroupLayout pnDadosEmpresaLayout = new javax.swing.GroupLayout(pnDadosEmpresa);
        pnDadosEmpresa.setLayout(pnDadosEmpresaLayout);
        pnDadosEmpresaLayout.setHorizontalGroup(
            pnDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        pnDadosEmpresaLayout.setVerticalGroup(
            pnDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados da Empresa", pnDadosEmpresa);

        tblUsuarios.setAutoCreateRowSorter(true);
        tblUsuarios.setRowHeight(24);
        jScrollPane1.setViewportView(tblUsuarios);

        btnPesquisaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Find.png"))); // NOI18N
        btnPesquisaUsuario.setText("Pesquisar");
        btnPesquisaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaUsuarioActionPerformed(evt);
            }
        });

        btnNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Add.png"))); // NOI18N
        btnNovoUsuario.setText("Novo");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });

        btnAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Modify.png"))); // NOI18N
        btnAlterarUsuario.setText("Alterar Usuario");
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarUsuario)
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaUsuario)
                    .addComponent(btnAlterarUsuario)
                    .addComponent(btnNovoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuários", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pastas"));

        jLabel17.setText("Logs de Erros");

        txtPastaLogErro.setEditable(false);
        txtPastaLogErro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPastaLogErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Folder.png"))); // NOI18N
        btnPastaLogErro.setEnabled(false);
        btnPastaLogErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastaLogErroActionPerformed(evt);
            }
        });

        jLabel18.setText("Arquivos de Backup");

        txtPastaBackup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPastaBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Folder.png"))); // NOI18N
        btnPastaBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastaBackupActionPerformed(evt);
            }
        });

        jLabel19.setText("Arquivos de Impressão");

        txtPastaImpressao.setEditable(false);
        txtPastaImpressao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPastaBackup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Folder.png"))); // NOI18N
        btnPastaBackup1.setEnabled(false);
        btnPastaBackup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastaBackup1ActionPerformed(evt);
            }
        });

        lblIp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIp.setText("jLabel3");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Versão:");

        lblVersao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVersao.setText("jLabel3");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Sistema Operacional:");

        lblSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSo.setText("jLabel3");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Usuário Windows:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("jLabel3");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Nome do Computador:");

        lblHost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHost.setText("jLabel3");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Endereço IP:");

        jLabel25.setText("Caminho do Sistema:");

        lblPathSistema.setText("jLabel26");

        jLabel29.setText("Documentos");

        txtPastaDocumentos.setEditable(false);
        txtPastaDocumentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPastaBackup2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Folder.png"))); // NOI18N
        btnPastaBackup2.setEnabled(false);
        btnPastaBackup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastaBackup2ActionPerformed(evt);
            }
        });

        txtPastaDados.setEditable(false);
        txtPastaDados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel30.setText("Banco de dados");

        btnPastaBackup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagens/18x18/Folder.png"))); // NOI18N
        btnPastaBackup3.setEnabled(false);
        btnPastaBackup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastaBackup3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIp))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVersao)))
                        .addGap(191, 191, 191)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblHost)))
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(lblPathSistema))
                    .addComponent(jLabel29)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPastaDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addComponent(txtPastaImpressao)
                            .addComponent(txtPastaBackup)
                            .addComponent(txtPastaLogErro)
                            .addComponent(txtPastaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPastaLogErro)
                            .addComponent(btnPastaBackup)
                            .addComponent(btnPastaBackup1)
                            .addComponent(btnPastaBackup2)
                            .addComponent(btnPastaBackup3)))
                    .addComponent(jLabel30))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPastaLogErro)
                    .addComponent(txtPastaLogErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPastaBackup)
                    .addComponent(txtPastaBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPastaBackup1)
                    .addComponent(txtPastaImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPastaBackup2)
                    .addComponent(txtPastaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPastaBackup3)
                    .addComponent(txtPastaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblSo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lblVersao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(lblIp)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblHost))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblPathSistema))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sistema", jPanel7);

        pnLogAcao.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Logs de Ação", pnLogAcao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        salvar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAddFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFotoActionPerformed
        addFoto();
    }//GEN-LAST:event_btnAddFotoActionPerformed

    private void btnRemFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemFotoActionPerformed
        removeFoto();
    }//GEN-LAST:event_btnRemFotoActionPerformed

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        // TODO add your handling code here:
        novoUsuario();
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        if (tblUsuarios.getSelectedRow() >=0)
            editarUsuario();
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnPesquisaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaUsuarioActionPerformed
        procurarUsuario();
    }//GEN-LAST:event_btnPesquisaUsuarioActionPerformed

    private void btnPastaLogErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastaLogErroActionPerformed
        
        JFileChooser fileChooser = new JFileChooser(pathFoto, null);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int aprove = fileChooser.showOpenDialog(null);
        if (aprove == JFileChooser.APPROVE_OPTION){
            System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnPastaLogErroActionPerformed

    private void btnPastaBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastaBackupActionPerformed
        JFileChooser fileChooser = new JFileChooser(pathFoto, null);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int aprove = fileChooser.showOpenDialog(null);
        if (aprove == JFileChooser.APPROVE_OPTION){
            txtPastaBackup.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnPastaBackupActionPerformed

    private void btnPastaBackup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastaBackup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPastaBackup1ActionPerformed

    private void btnPastaBackup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastaBackup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPastaBackup2ActionPerformed

    private void btnPesquisaCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCEPActionPerformed
        searchEndereco();
    }//GEN-LAST:event_btnPesquisaCEPActionPerformed

    private void btnPastaBackup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastaBackup3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPastaBackup3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConfiguracoes dialog = new DlgConfiguracoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFoto;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnPastaBackup;
    private javax.swing.JButton btnPastaBackup1;
    private javax.swing.JButton btnPastaBackup2;
    private javax.swing.JButton btnPastaBackup3;
    private javax.swing.JButton btnPastaLogErro;
    private javax.swing.JButton btnPesquisaCEP;
    private javax.swing.JButton btnPesquisaUsuario;
    private javax.swing.JButton btnRemFoto;
    private javax.swing.JComboBox cmbUf;
    private javax.swing.JEditorPane edpAnotacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblPathSistema;
    private javax.swing.JLabel lblSo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JPanel pnDadosEmpresa;
    private javax.swing.JPanel pnLogAcao;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPastaBackup;
    private javax.swing.JTextField txtPastaDados;
    private javax.swing.JTextField txtPastaDocumentos;
    private javax.swing.JTextField txtPastaImpressao;
    private javax.swing.JTextField txtPastaLogErro;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getDataForm() {
        cfg.setConfNomeFantasia(txtNomeFantasia.getText());
        cfg.setConfRazaoSocial(txtRazaoSocial.getText());
        cfg.setConfCNPJ(txtCnpj.getText());
        cfg.setTelefone(txtTelefone.getText());
        cfg.setSite(txtSite.getText());
        cfg.setEmail(txtEmail.getText());
        cfg.setNumeroEndereco(txtNumero.getText());
        cfg.setAnotacoes(edpAnotacoes.getText());
        cfg.setPathBackup(txtPastaBackup.getText());
        
        cfg.setEndereco(getEnderecoForm());
        
        return cfg;
    }
    
    @Override
    public void setDataForm(Object objeto) {
        cfg = (Configuracoes) objeto;
        
        txtNomeFantasia.setText(cfg.getConfNomeFantasia());
        txtRazaoSocial.setText(cfg.getConfRazaoSocial());
        txtCnpj.setText(cfg.getConfCNPJ());
        txtNumero.setText(cfg.getNumeroEndereco());
        txtTelefone.setText(cfg.getTelefone());
        txtSite.setText(cfg.getSite());
        txtEmail.setText(cfg.getEmail());
        edpAnotacoes.setText(cfg.getAnotacoes());
        
        if (cfg.getConfLogomarca() != null) {
            setFoto();    
            btnAddFoto.setEnabled(false);
            btnRemFoto.setEnabled(true);
        } else {
            setFoto();
            btnAddFoto.setEnabled(true);
            btnRemFoto.setEnabled(false);
        }
        
        
        setEnderecoForm(cfg.getEndereco());
        
        // painel sistema
        txtPastaLogErro.setText(cfg.getPathLogErros());
        txtPastaBackup.setText(cfg.getPathBackup());
        txtPastaImpressao.setText(cfg.getPathArquivosImpressao());
        txtPastaDocumentos.setText(cfg.getPathDocumentos());
        txtPastaDados.setText(cfg.getPathFotos());//dados usa fotos
    }

    @Override
    public void salvar() {
        
        controllerCfg.setObject(getDataForm());
        
        if(controllerCfg.update()){
            ShowMessage.informationMessage("Configurações salvas com sucesso!");
        }
        
    }//fim save

    @Override
    public void novo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void fechar() {
        dispose();
    }

    
    public void novoUsuario() {
        FrmCadastroUsuario fcu = new FrmCadastroUsuario(null, rootPaneCheckingEnabled);
        fcu.novo();
        fcu.setVisible(rootPaneCheckingEnabled);
        procurarUsuario();
    }

    private void procurarUsuario() {
        UsuarioController uc;
        uc = new UsuarioController();
        String query = "SELECT u FROM Usuario u where UPPER(u.login) like UPPER(:param) "
                + "OR UPPER(u.email) like UPPER(:param)"
                + "  ORDER BY u.login asc";
        
        List<Usuario> findByParameters = uc.findByParameters(query,"%"+txtPesquisa.getText()+"%");
        usuarios = (List<Usuario>) findByParameters;
        
        MyTableModel mtm = new MyTableModel();
        mtm.setColunas(new String[]{"Login","Email","Ativo"});
        int[] sizeColumns = {100,100,100};
        
        for (Usuario u : usuarios){
            mtm.addRow(new Object[]{u.getLogin(),u.getEmail(),u.isAtivo()});
        }
        
        tblUsuarios.setModel(mtm);
        for (int i=0;i< sizeColumns.length;i++){
            tblUsuarios.getColumnModel().getColumn(i).setPreferredWidth(sizeColumns[i]);
        }
    }

    public void editarUsuario() {
        /**
         * Pegar usuario com getDataRow, inserir em um novo usuario e passar via setUsuario para FrmAlterarSenha.
         */
        FrmCadastroUsuario fcu = new FrmCadastroUsuario(null, rootPaneCheckingEnabled);
        UsuarioBO udao = new UsuarioBO();
        Usuario usuario = usuarios.get(tblUsuarios.getSelectedRow());
        
        try {
            if (udao.findById(usuario.getLogin()) != null ){
                fcu.setEditar(usuario);
                fcu.setVisible(true);
                procurarUsuario();
            }
        } catch (SQLException ex) {
            Log.log(DlgConfiguracoes.class.getName(), ex);
        } catch (Exception ex) {
            Log.log(DlgConfiguracoes.class.getName(), ex);
        }
    }

    private void searchEndereco() {
        EnderecoController cEndereco = new EnderecoController();
        endereco = cEndereco.findByCep(txtCep.getText()); // se não ouver nada retorna null
        if (endereco == null){
            FrmPesquisaEndereco fe = new FrmPesquisaEndereco(null, true);
            fe.setVisible(true);
            endereco = fe.getEndereco();
        }
        setEnderecoForm(endereco);
    }//fim search

    private Endereco getEnderecoForm() {
        //GARNTE A NOVA INSTANCIA PARA ENDERECO
        if (endereco == null){
            endereco = new Endereco();
        }
        endereco.setLogradouro(txtEndereco.getText());
        endereco.setBairro(txtBairro.getText());
        endereco.setCep(txtCep.getText());
        endereco.setCidade(txtCidade.getText());
        endereco.setUf(Estados.valueOf(cmbUf.getSelectedItem().toString()).name());
        
        return endereco;
    }

    private void setEnderecoForm(Endereco endereco) {
        //SE HOUVER UMA INSTACIA APROVEITA A MESMA
        if (endereco instanceof Endereco)
            this.endereco = endereco;
        else endereco = new Endereco();
        
        txtEndereco.setText(endereco.getLogradouro());
        txtBairro.setText(endereco.getBairro());
        txtCep.setText(endereco.getCep());
        txtCidade.setText(endereco.getCidade());
        cmbUf.setSelectedItem(Estados.valueOf(endereco.getUf()));
    }
    
    /**
     * Este método é essencial em todos os forms do sistema pois é ele quem garante o acesso
     * ao sistema.
     */
    @Override
    public void verPermissao(){
        enableControls(false);
        Usuario usuario = Sessao.getInstance().getUsuario();
        if (usuario.isAllowed(CasoUso.CONFIGURACOES_SISTEMA)){
            
            for (Permissao per : usuario.getPermissaos(CasoUso.CONFIGURACOES_SISTEMA)){
                
                switch(per){
                    case LER:
                        btnPesquisaUsuario.setEnabled(true);
                        break;
                    case CRIAR:
                        btnConfirmar.setEnabled(true);
                        btnNovoUsuario.setEnabled(true);
                        break;
                    case EDITAR:
                        btnConfirmar.setVisible(true);
                        btnAlterarUsuario.setEnabled(true);
                        break;
                    case EXCLUIR:
                        
                        break;
                }//fim switch
            } //fim for
        } else {
            ShowMessage.informationMessage("Você não possui acesso a esta área!");
            fechar();
        }//fim se tiver permissão
        
        //se ele não pode ver então encerra caso
        if (!usuario.isAllowed(CasoUso.CONFIGURACOES_SISTEMA, Permissao.LER)) {
            ShowMessage.informationMessage("Você não possui acesso a esta área!");
            dispose();
        }
    }//fim verpermissoes
    
   
    @Override
    public void editar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void excluir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void localizar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void enableControls(boolean bool) {
        btnConfirmar.setEnabled(bool);
        btnAlterarUsuario.setEnabled(bool);
        btnNovoUsuario.setEnabled(bool);
    }

    @Override
    public void enableForm(boolean bool) {
        
        txtNomeFantasia.setEditable(bool);
        txtRazaoSocial.setEditable(bool);
        txtCnpj.setEditable(bool);
        txtNumero.setEditable(bool);
        txtTelefone.setEditable(bool);
        txtSite.setEditable(bool);
        txtEmail.setEditable(bool);
        edpAnotacoes.setEditable(bool);
        txtPastaBackup.setEditable(bool);
        btnAddFoto.setEnabled(bool);
        btnRemFoto.setEnabled(bool);
        btnPastaBackup.setEnabled(bool);
        
        btnPesquisaCEP.setEnabled(bool);
        txtEndereco.setEditable(bool);
        txtBairro.setEditable(bool);
        txtCep.setEditable(bool);
        txtCidade.setEditable(bool);
        cmbUf.setEnabled(bool);
        
        btnAddFoto.setEnabled(bool);
        btnRemFoto.setEnabled(bool);
    }
    
    private void addFoto(){
        
        //abre o filechooser
        JFileChooser fl = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens JPG", "jpg","jpeg");
        fl.setFileFilter(filtro);
        
        fl.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int val = fl.showDialog(this, "Selecionar");
        
        if (val == JFileChooser.APPROVE_OPTION) {
            try {
                
                //verifica a existencia do diretorio de documentos
                // pathAbsoluto + pathRelativo
                System.out.println(pathAbsoluto + pathRelativo);
                File out = new File(pathAbsoluto + pathRelativo);
                
                if (!out.exists())
                    out.mkdirs();
                
                //Abre o arquivo selecionado para transferencia com path original
                FileInputStream inFile = new FileInputStream(fl.getSelectedFile()); 
                
                //criar o arquivo bruto de saida
                // arquivo documentos + nome do novo arquivo
                String pathOut = out.toString()+"/"+fl.getSelectedFile().getName();
                
                System.out.println(pathOut);
                //abre o fluxo para transferir o novo arquivo
                FileOutputStream outFile = new FileOutputStream(new File(pathOut));
                
                //coloca o caminho relativo no banco
                cfg.setConfLogomarca(pathRelativo+"/"+fl.getSelectedFile().getName());

                //faz a transferencia
                FileChannel origem = inFile.getChannel();
                FileChannel destino = outFile.getChannel();
                origem.transferTo(0, origem.size(), destino);
                origem.close();
                destino.close();
                inFile.close();
                outFile.close();

                setFoto();
                btnRemFoto.setEnabled(true);
                btnAddFoto.setEnabled(false);
//              
            } catch (FileNotFoundException ex) {
                Log.log(DlgConfiguracoes.class.getName(), ex);
            } catch (IOException ex) {
                Log.log(DlgConfiguracoes.class.getName(), ex);
            }
        }//fim se val

    }//fim addFoto()

    private void removeFoto() {
        if (pathAbsoluto + cfg.getConfLogomarca() != null) {
            File foto = new File(pathAbsoluto + cfg.getConfLogomarca());
            if (foto.exists()){
                if(foto.delete()){
                    cfg.setConfLogomarca(null);
                    setFoto();
                    btnRemFoto.setEnabled(false);
                    btnAddFoto.setEnabled(true);
                }//fim se apagar foto do windows
            }//fim se a foto exisitr
        }//fim se logomarca não nulo
    }
    
    private void setFoto(){
        
        ImageIcon ico = new ImageIcon(pathAbsoluto + cfg.getConfLogomarca());
        ico.setImage(ico.getImage().getScaledInstance(lblFoto.getWidth()-10, lblFoto.getHeight(), 50));
        lblFoto.setIcon(ico);
        
    }
}//fim classe